{
  "Uuid": "adf0ff4b-dd5a-4fe4-be94-012ca7434b47",
  "IsCustomNode": false,
  "Description": null,
  "Name": "ProjectOnTo",
  "ElementResolver": {
    "ResolutionMap": {}
  },
  "Inputs": [],
  "Outputs": [],
  "Nodes": [
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "NodeType": "FunctionNode",
      "FunctionSignature": "Autodesk.DesignScript.Geometry.Point.ByCoordinates@double,double,double",
      "Id": "4af3c6e8130540b0bd3e78633a1d51f2",
      "Inputs": [
        {
          "Id": "89e2e14d2c404264990abe2c8ea30be0",
          "Name": "x",
          "Description": "double\nDefault value : 0",
          "UsingDefaultValue": true,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "c36219d166bc4287ba18d9940ff866c5",
          "Name": "y",
          "Description": "double\nDefault value : 0",
          "UsingDefaultValue": true,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "db06e8a93b4c4d478e43579084836da9",
          "Name": "z",
          "Description": "double\nDefault value : 0",
          "UsingDefaultValue": true,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "b372c8300a524968862640d3f7c6156a",
          "Name": "Point",
          "Description": "Point",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Auto",
      "Description": "Form a Point given 3 cartesian coordinates\n\nPoint.ByCoordinates (x: double = 0, y: double = 0, z: double = 0): Point"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "NodeType": "FunctionNode",
      "FunctionSignature": "Autodesk.DesignScript.Geometry.Plane.ByOriginNormal@Autodesk.DesignScript.Geometry.Point,Autodesk.DesignScript.Geometry.Vector",
      "Id": "ce5351af694b426e97ef3da7d2e8ab31",
      "Inputs": [
        {
          "Id": "98db101d34054869832c226d7498e6a6",
          "Name": "origin",
          "Description": "Point\nDefault value : Autodesk.DesignScript.Geometry.Point.ByCoordinates(0, 0, 0)",
          "UsingDefaultValue": true,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "d638a39347934ae0a1dd1d9046444231",
          "Name": "normal",
          "Description": "Vector\nDefault value : Autodesk.DesignScript.Geometry.Vector.ByCoordinates(0, 0, 1)",
          "UsingDefaultValue": true,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "67de3bc4ae4842a1a70110a13f8b999d",
          "Name": "Plane",
          "Description": "Plane",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Auto",
      "Description": "Create a Plane centered at root Point, with input normal Vector.\n\nPlane.ByOriginNormal (origin: Point = Autodesk.DesignScript.Geometry.Point.ByCoordinates(0, 0, 0), normal: Vector = Autodesk.DesignScript.Geometry.Vector.ByCoordinates(0, 0, 1)): Plane"
    },
    {
      "ConcreteType": "CoreNodeModels.Input.DoubleSlider, CoreNodeModels",
      "NodeType": "NumberInputNode",
      "NumberType": "Double",
      "MaximumValue": 10.0,
      "MinimumValue": 0.0,
      "StepValue": 0.01,
      "InputValue": 6.16,
      "Id": "3b5bc8625a1747779983026652345015",
      "Inputs": [],
      "Outputs": [
        {
          "Id": "b82d62461eaa4992a9e429a1cedf40cf",
          "Name": "",
          "Description": "Double",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Disabled",
      "Description": "A slider that produces numeric values."
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.CustomNodes.Function, DynamoCore",
      "FunctionSignature": "320b89c0-60da-4def-9c24-d7f2713019ab",
      "FunctionType": "Graph",
      "NodeType": "FunctionNode",
      "Id": "f4e4a9dfdb0349b2aacd5c01cfd5f428",
      "Inputs": [
        {
          "Id": "0312b47753224df18b65e43936be8858",
          "Name": "vector",
          "Description": "Vector",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "f78669712e2341c4ae72adabb9fe9f66",
          "Name": "plane",
          "Description": "Plane\nDefault value : Autodesk.DesignScript.Geometry.Plane.XY()",
          "UsingDefaultValue": true,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "8737773d315a433684ebe959f683e048",
          "Name": "vector",
          "Description": "return value",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Auto",
      "Description": "Find the projection of the vector to the specified plane."
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "NodeType": "FunctionNode",
      "FunctionSignature": "Autodesk.DesignScript.Geometry.Point.AsVector",
      "Id": "480ece2bb00f437ab111215ef04aa0b3",
      "Inputs": [
        {
          "Id": "d142c827fdf2469d997168b1b48f73de",
          "Name": "point",
          "Description": "Autodesk.DesignScript.Geometry.Point",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "2f4b8d66bd7e41099ad9eb2b408bc14b",
          "Name": "Vector",
          "Description": "Vector",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Auto",
      "Description": "Get the Vector with the same X, Y, and Z component\n\nPoint.AsVector ( ): Vector"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "NodeType": "FunctionNode",
      "FunctionSignature": "Autodesk.DesignScript.Geometry.Vector.AsPoint",
      "Id": "9ea230f459be44c991546a5fc1776e7c",
      "Inputs": [
        {
          "Id": "2803a547c56e458794b6bdce5cbd3567",
          "Name": "vector",
          "Description": "Autodesk.DesignScript.Geometry.Vector",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "64aa05787faf45c58cdfc93b902f3f3e",
          "Name": "Point",
          "Description": "Point",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Auto",
      "Description": "Get the Point with the same X, Y, and Z component\n\nVector.AsPoint ( ): Point"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "NodeType": "FunctionNode",
      "FunctionSignature": "Autodesk.DesignScript.Geometry.Vector.YAxis",
      "Id": "cd1db5ece95b476eb853ce1c60e2e21f",
      "Inputs": [],
      "Outputs": [
        {
          "Id": "9e092b1f9cb7480fbd7de1ac1f739c13",
          "Name": "Vector",
          "Description": "Vector",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Auto",
      "Description": "Get the canonical Y axis Vector (0,1,0)\n\nVector.YAxis ( ): Vector"
    }
  ],
  "Connectors": [
    {
      "Start": "b372c8300a524968862640d3f7c6156a",
      "End": "d142c827fdf2469d997168b1b48f73de",
      "Id": "067d6c237c864dbfb7f83b171a071753"
    },
    {
      "Start": "67de3bc4ae4842a1a70110a13f8b999d",
      "End": "f78669712e2341c4ae72adabb9fe9f66",
      "Id": "0258a6b92a5047b3861325ea56fca536"
    },
    {
      "Start": "b82d62461eaa4992a9e429a1cedf40cf",
      "End": "89e2e14d2c404264990abe2c8ea30be0",
      "Id": "685da0accc044bc38840deb3aa8d4536"
    },
    {
      "Start": "b82d62461eaa4992a9e429a1cedf40cf",
      "End": "c36219d166bc4287ba18d9940ff866c5",
      "Id": "75fdabe7e768442ebfd952808c926abc"
    },
    {
      "Start": "8737773d315a433684ebe959f683e048",
      "End": "2803a547c56e458794b6bdce5cbd3567",
      "Id": "48db85e1d7d34fddac5e695631676427"
    },
    {
      "Start": "2f4b8d66bd7e41099ad9eb2b408bc14b",
      "End": "0312b47753224df18b65e43936be8858",
      "Id": "7d3f27d206da4e8ea53db97c121f5c2f"
    },
    {
      "Start": "9e092b1f9cb7480fbd7de1ac1f739c13",
      "End": "d638a39347934ae0a1dd1d9046444231",
      "Id": "86915364c4c04c2aaef7fbf40ca40824"
    }
  ],
  "Dependencies": [
    "320b89c0-60da-4def-9c24-d7f2713019ab"
  ],
  "Bindings": [],
  "View": {
    "Dynamo": {
      "ScaleFactor": 1.0,
      "HasRunWithoutCrash": true,
      "IsVisibleInDynamoLibrary": true,
      "Version": "2.1.0.7500",
      "RunType": "Automatic",
      "RunPeriod": "1000"
    },
    "Camera": {
      "Name": "Background Preview",
      "EyeX": -9.8418094464819088,
      "EyeY": 8.0070297828639188,
      "EyeZ": -12.316105437884991,
      "LookX": 9.97619590111052,
      "LookY": -6.7210251756183421,
      "LookZ": 7.4331482410713523,
      "UpX": 0.22102987880861441,
      "UpY": 0.96126169593835986,
      "UpZ": 0.16468680759441964
    },
    "NodeViews": [
      {
        "ShowGeometry": true,
        "Name": "Point.ByCoordinates",
        "Id": "4af3c6e8130540b0bd3e78633a1d51f2",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": 554.1564010807972,
        "Y": 325.60916898780221
      },
      {
        "ShowGeometry": true,
        "Name": "Plane.ByOriginNormal",
        "Id": "ce5351af694b426e97ef3da7d2e8ab31",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": 466.51747842907929,
        "Y": 166.80971338187308
      },
      {
        "ShowGeometry": true,
        "Name": "Number Slider",
        "Id": "3b5bc8625a1747779983026652345015",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": 157.2153701679872,
        "Y": 435.76213376440097
      },
      {
        "ShowGeometry": true,
        "Name": "Vector.ProjectToPlane",
        "Id": "f4e4a9dfdb0349b2aacd5c01cfd5f428",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": 1050.9566738485266,
        "Y": 192.09396920917004
      },
      {
        "ShowGeometry": true,
        "Name": "Point.AsVector",
        "Id": "480ece2bb00f437ab111215ef04aa0b3",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": 785.86832970953242,
        "Y": 311.57106669149522
      },
      {
        "ShowGeometry": true,
        "Name": "Vector.AsPoint",
        "Id": "9ea230f459be44c991546a5fc1776e7c",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": 1322.8542401071018,
        "Y": 325.8454140580875
      },
      {
        "ShowGeometry": true,
        "Name": "Vector.YAxis",
        "Id": "cd1db5ece95b476eb853ce1c60e2e21f",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": 232.26515275373623,
        "Y": 261.94789214929125
      }
    ],
    "Annotations": [],
    "X": -125.02871222485317,
    "Y": 4.4689357683623712,
    "Zoom": 0.96023320580218008
  }
}